const SUPPORTED_GATEWAYS = [
  {
    id: "razorpay",
    label: "Razorpay",
    description: "Cards, UPI, Net Banking, Wallets",
    docsUrl: "https://razorpay.com/docs/api/",
    setupNote: "Use Test keys from Razorpay Dashboard (Sandbox Mode).",
    keyIdLabel: "Key ID",
    keySecretLabel: "Key Secret",
    checkoutMode: "native",
    isIntegrated: true,
  },
  {
    id: "cashfree",
    label: "Cashfree",
    description: "Cards, UPI, Net Banking, Wallets",
    docsUrl: "https://docs.cashfree.com/",
    setupNote: "Create Test App in dashboard to generate API keys.",
    keyIdLabel: "App ID",
    keySecretLabel: "Secret Key",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "paytm",
    label: "Paytm",
    description: "UPI, Wallet, Cards, Net Banking",
    docsUrl: "https://developer.paytm.com/",
    setupNote: "Get staging credentials after merchant signup.",
    keyIdLabel: "MID / Merchant ID",
    keySecretLabel: "Merchant Key",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "payu",
    label: "PayU India",
    description: "UPI, Net Banking, Wallets",
    docsUrl: "https://www.payu.in/developer/api",
    setupNote: "Use sandbox Merchant Key and Salt from merchant dashboard.",
    keyIdLabel: "Merchant Key",
    keySecretLabel: "Salt",
    checkoutMode: "native",
    isIntegrated: true,
  },
  {
    id: "instamojo",
    label: "Instamojo",
    description: "UPI, Cards, Net Banking",
    docsUrl: "https://docs.instamojo.com/",
    setupNote: "Enable Test Mode to get API Key and Auth Token.",
    keyIdLabel: "API Key",
    keySecretLabel: "Auth Token",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "ccavenue",
    label: "CCAvenue",
    description: "Cards, Net Banking, Wallets",
    docsUrl: "https://www.ccavenue.com/",
    setupNote: "Sandbox access is provided by support on request.",
    keyIdLabel: "Merchant ID",
    keySecretLabel: "Working Key",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "phonepe",
    label: "PhonePe",
    description: "UPI, Cards, Wallet",
    docsUrl: "https://developer.phonepe.com/",
    setupNote: "Sandbox access is available after onboarding approval.",
    keyIdLabel: "Merchant ID",
    keySecretLabel: "Salt Key / Secret",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "mobikwik",
    label: "MobiKwik",
    description: "Wallet, UPI, Cards",
    docsUrl: "https://www.mobikwik.com/",
    setupNote: "Merchant onboarding is required before sandbox approval.",
    keyIdLabel: "Merchant ID",
    keySecretLabel: "Secret Key",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "juspay",
    label: "Juspay",
    description: "Orchestration, UPI, Cards, Wallets",
    docsUrl: "https://juspay.io/docs",
    setupNote: "Sandbox keys are shared after merchant onboarding.",
    keyIdLabel: "Merchant ID",
    keySecretLabel: "API Key / Secret",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "easebuzz",
    label: "Easebuzz",
    description: "UPI, Cards, Net Banking",
    docsUrl: "https://docs.easebuzz.in/",
    setupNote: "Use Merchant Key and Salt in Test Mode from dashboard.",
    keyIdLabel: "Merchant Key",
    keySecretLabel: "Salt",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
  {
    id: "stripe",
    label: "Stripe",
    description: "Cards, Wallets, Global Payments",
    docsUrl: "https://stripe.com/docs/api",
    setupNote: "Use test API keys from Stripe dashboard.",
    keyIdLabel: "Publishable Key",
    keySecretLabel: "Secret Key",
    checkoutMode: "redirect",
    isIntegrated: true,
  },
];

const SUPPORTED_GATEWAY_IDS = SUPPORTED_GATEWAYS.map((gateway) => gateway.id);

const getGatewayMeta = (gatewayId) =>
  SUPPORTED_GATEWAYS.find((gateway) => gateway.id === gatewayId) || null;

module.exports = {
  SUPPORTED_GATEWAYS,
  SUPPORTED_GATEWAY_IDS,
  getGatewayMeta,
};
